### PR TITLE
support ts3.7

### PR DESCRIPTION
**Pull request by ipcjs**
The latest version of typescript-eslint supports the new syntax of ts3.7
https://github.com/typescript-eslint/typescript-eslint/issues/1033

### CODE REVIEW

**Comment by doits** [comment]
:+1: anything keeping this from being merged and a new version released?

**Comment by ipcjs** [comment]
This configuration works fine in my project.😅
Those breaking changes don't seem to affect this package.

**Comment by ipcjs** [comment]
If you want to use it now, just execute  `npm i git+https://github.com/ipcjs/eslint-config-typescript.git`
👌

**Comment by sodatea** [comment]
I'll do the release this week.

**Pull request merged**
