### PR TITLE
feat: simplify the `*-type-checked` configs by providing a meaningful and performant default

### PR DESCRIPTION
**Pull request by haoqunjiang**
I finally figured out how to do this intuitively and performantly.

I still need to adjust the example project structure a bit and set up the tests but this is the gist.

### CODE REVIEW

**Comment by DrJume** [comment]
There is also a volar eslint integration: @volar/eslint https://github.com/volarjs/volar.js/tree/master/packages/eslint.

Can it be included as well? It would support everything the IDE extension already supports.

Here is the PR with an example:

https://github.com/volarjs/volar.js/pull/171

**Comment by basil** [comment]
Causes https://github.com/neanes/neanes/pull/1030#pullrequestreview-2367528558.

**Comment by haoqunjiang** [comment]
@basil Fixed in 14.1.1. Could you try it out?

**Comment by haoqunjiang** [comment]
@DrJume
It's the first time I got to know this package… Thanks for the information! I will talk to Johnson to see if it's production-ready and how it works with the rest of the ecosystem.

**Comment by basil** [comment]
@haoqunjiang We have successfully upgraded to 14.1.1 in https://github.com/neanes/neanes/pull/1038. Thanks!

**Comment by DrJume** [comment]
> @DrJume It's the first time I got to know this package… Thanks for the information! I will talk to Johnson to see if it's production-ready and how it works with the rest of the ecosystem.

You're welcome! Thank you for taking a look at it. This would be so great to have!

**Pull request merged**
